FROM node:22 as base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable


FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
# Install Bun
RUN pnpm install -g bun
RUN sh ./turso_install.sh

EXPOSE 3000
EXPOSE 3001
EXPOSE 3002

ENTRYPOINT [ "sh", "./start.sh" ]